### ISSUE TITLE
several build errors

### ISSUE THREAD

**Issue by jnorwood** [Apress/pro-TBB#2]
I cloned these examples and attemped to build with g++ on ubuntu 18.04LTS.  There were a number of errors.  I think I resolved the path issues.   I sourced the attached "doit.txt" command to set up the environment and build all the examples. I'm attaching doit.log which shows the successes and errors.

[doit.txt](https://github.com/Apress/pro-TBB/files/5011001/doit.txt)

[doit.log](https://github.com/Apress/pro-TBB/files/5011002/doit.log)

**Comment by jnorwood** [comment]
I modified my build script to run the setup shell scripts described in the book on p18.

```
export TBB_ROOT="/home/jay/tbb_bin/tbb-2020.3-lin/tbb"
export PSTL_ROOT="/home/jay/tbb_bin/tbb-2020.3-lin/pstl"
source ${TBB_ROOT}/bin/tbbvars.sh intel64 linux auto_tbbroot
source ${PSTL_ROOT}/bin/pstlvars.sh intel64 auto_pstlroot
make CXX=g++ ch01

```
That gets rid of some errors, but still several failures, for example  in the second example of ch01

```
g++  -std=c++11 -O2 -g -o fig_1_05 fig_1_05.cpp -ltbb
/tmp/cceo0TwC.o: In function `main':
/home/jay/tbb_bin/tbb-2020.3-lin/tbb/include/tbb/task_arena.h:216: undefined reference to `tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
collect2: error: ld returned 1 exit status


```

**Comment by jnorwood** [comment]
I discovered that using the _debug suffix versions of the libraries cleaned up the undefined reference errors when building with -g option.  In other words, go through all the Makefiles and change -ltbb to -ltbb_debug.

I haven't looked to see if this is mentioned in the book, but it does fix all of this type of build error.
